Make old tracing runtimes (<700) compile
PureStake/moonbeam-runtime-overrides pull request #33
Opened 2022-01-06 13:45 UTC by librelois

2022-01-07 10:39 UTC, nanocryk requested changes

2022-01-07 10:39 UTC, nanocryk commented on tracing/300/runtime/moonbase/Cargo.toml
>  evm-tracing-events = { path = "../../../shared/primitives/rpc/evm-tracing-events", default-features = false, optional = true }
no `features = ["before_1200"]` like the other runtimes ?

2022-01-07 10:39 UTC, nanocryk commented on tracing/300/runtime/moonriver/Cargo.toml
>  evm-tracing-events = { path = "../../../shared/primitives/rpc/evm-tracing-events", default-features = false, optional = true }
no `features = ["before_1200"]` like the other runtimes ?

2022-01-07 10:52 UTC, librelois commented
@nanocryk refactored to remove feature `before_1200`

2022-01-07 11:19 UTC, nanocryk approved these changes
Awesome ! 2 From impl are definitely better

2022-01-07 11:24 UTC, librelois commented
@tgmichel I would like your review too

2022-01-10 13:33 UTC, tgmichel commented
I think we should also patch `ethereum` crate in:

- tracing/700/Cargo.toml
- tracing/701/Cargo.toml
- tracing/801/Cargo.toml

`ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info" }`

2022-01-10 13:40 UTC, tgmichel approved these changes
Aside from the comment lgtm!

2022-01-10 13:50 UTC, tgmichel commented
> 

Right!

2022-01-10 14:44 UTC, merged